name: Release

on:
  push:
    branches:
      - alex/publish-canary

concurrency: ${{ github.workflow}}-${{ github.ref }}

jobs:
  release:
    name: Canary Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Merge To Canary Branch
        run: |
          git checkout practice-canary
          git merge origin/main --strategy-option=theirs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Now we pre-release
      - name: Enter Pre-Release Mode
        run: |
          pnpm exec changeset pre enter canary
          pnpm exec changeset version

      - name: Commit Change To Pre-Release Mode
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Enter prerelease mode and version packages'
          branch: practice-canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: |
          echo "This is when publish would run.."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push Changes To Branch
        run: git push origin practice-canary --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
