name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow}}-${{ github.ref }}

jobs:
  test:
    name: Build and E2E Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Install Playwright Browsers
        run: pnpm -F "*e2e*" exec playwright install --with-deps

      - name: Build
        run: pnpm run build

      - name: Run e2e tests
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: e2e/**/playwright-report/
          retention-days: 30
