name: Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency: ${{ github.workflow}}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Test packages
        run: yarn run test
